# Generated by Django 2.2.5 on 2021-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=20)),
                ('full_address', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('old_district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restuarant',
            },
        ),
    ]
