# Generated by Django 2.2.5 on 2021-10-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('search_keyword', models.CharField(max_length=200)),
                ('food_keyword', models.TextField(blank=True, null=True)),
                ('region_keyword', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_search_log',
            },
        ),
    ]
